version: "2"

# all available settings of specific linters
linters:
  default: none
  enable:
    - errcheck
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - govet
  settings:
    errcheck:
      exclude-functions:
        - "(*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set"
  exclusions:
    rules:
      - text: "GetOkExists"
        linters:
          - staticcheck

formatters:
  enable:
    - gofmt
    - goimports
